package models

import (
	"time"

	"go.mongodb.org/mongo-driver/bson/primitive"
)

// TronTaskStatus represents the status of a task
type TronTaskStatus string

const (
	TaskStatusBacklog   TronTaskStatus = "backlog"
	TaskStatusReady     TronTaskStatus = "ready"      // Approved by PM, ready for dev
	TaskStatusInDev     TronTaskStatus = "in_dev"
	TaskStatusInReview  TronTaskStatus = "in_review"
	TaskStatusDone      TronTaskStatus = "done"
	TaskStatusRejected  TronTaskStatus = "rejected"
)

// TronSourceLens represents the lens used to generate the task
type TronSourceLens string

const (
	LensMarket     TronSourceLens = "market"      // Mirror market reference
	LensExpansion  TronSourceLens = "expansion"   // Expand from last feature
	LensPersona    TronSourceLens = "persona"     // User persona perspective
	LensCode       TronSourceLens = "code"        // Code analysis (debt, tests)
	LensIntegration TronSourceLens = "integration" // Cross-repo update
	LensDirective  TronSourceLens = "directive"   // CIO directive
)

// TronTaskSize represents estimated task size
type TronTaskSize string

const (
	TaskSizeSmall  TronTaskSize = "small"  // 1 commit
	TaskSizeMedium TronTaskSize = "medium" // 2-3 commits
	TaskSizeLarge  TronTaskSize = "large"  // 4+ commits
)

// TronTaskPriority represents task priority
type TronTaskPriority string

const (
	PriorityLow      TronTaskPriority = "low"
	PriorityNormal   TronTaskPriority = "normal"
	PriorityHigh     TronTaskPriority = "high"
	PriorityCritical TronTaskPriority = "critical"
)

// TronTaskSpec represents the technical specification for a task
type TronTaskSpec struct {
	What               string   `json:"what" bson:"what"`
	FilesToCreate      []string `json:"files_to_create" bson:"files_to_create"`
	FilesToModify      []string `json:"files_to_modify" bson:"files_to_modify"`
	AcceptanceCriteria []string `json:"acceptance_criteria" bson:"acceptance_criteria"`
	TestsRequired      bool     `json:"tests_required" bson:"tests_required"`
	EdgeCases          []string `json:"edge_cases" bson:"edge_cases"`
}

// TronTaskCommit represents a commit made for the task
type TronTaskCommit struct {
	SHA       string    `json:"sha" bson:"sha"`
	Message   string    `json:"message" bson:"message"`
	FilesChanged int    `json:"files_changed" bson:"files_changed"`
	Additions int       `json:"additions" bson:"additions"`
	Deletions int       `json:"deletions" bson:"deletions"`
	CreatedAt time.Time `json:"created_at" bson:"created_at"`
}

// TronQAResult represents the QA review result
type TronQAResult struct {
	Result   string            `json:"result" bson:"result"` // APPROVED, NEEDS_FIX, REJECTED
	Feedback string            `json:"feedback" bson:"feedback"`
	Issues   []TronQAIssue     `json:"issues" bson:"issues"`
	Checks   TronQAChecks      `json:"checks" bson:"checks"`
	ReviewedAt time.Time       `json:"reviewed_at" bson:"reviewed_at"`
}

// TronQAIssue represents an issue found by QA
type TronQAIssue struct {
	File     string `json:"file" bson:"file"`
	Line     int    `json:"line" bson:"line"`
	Issue    string `json:"issue" bson:"issue"`
	Severity string `json:"severity" bson:"severity"` // minor, major
}

// TronQAChecks represents automated checks
type TronQAChecks struct {
	BuildPassed      bool    `json:"build_passed" bson:"build_passed"`
	TestsPassed      bool    `json:"tests_passed" bson:"tests_passed"`
	LinterClean      bool    `json:"linter_clean" bson:"linter_clean"`
	CoverageChange   float64 `json:"coverage_change" bson:"coverage_change"` // Positive or negative
}

// TronTask represents a task generated by the PM agent
type TronTask struct {
	ID            primitive.ObjectID   `json:"id" bson:"_id,omitempty"`
	UserID        primitive.ObjectID   `json:"user_id" bson:"user_id"`
	RepoID        primitive.ObjectID   `json:"repo_id" bson:"repo_id"`
	ProjectID     primitive.ObjectID   `json:"project_id" bson:"project_id"`
	Title         string               `json:"title" bson:"title"`
	Description   string               `json:"description" bson:"description"`
	Spec          TronTaskSpec         `json:"spec" bson:"spec"`
	Status        TronTaskStatus       `json:"status" bson:"status"`
	SourceLens    TronSourceLens       `json:"source_lens" bson:"source_lens"`
	Reasoning     string               `json:"reasoning" bson:"reasoning"` // Why this task was generated
	Priority      TronTaskPriority     `json:"priority" bson:"priority"`
	DependsOn     []primitive.ObjectID `json:"depends_on" bson:"depends_on"`
	Unlocks       []string             `json:"unlocks" bson:"unlocks"` // What this task enables
	EstimatedSize TronTaskSize         `json:"estimated_size" bson:"estimated_size"`
	BranchName    string               `json:"branch_name" bson:"branch_name"`
	Commits       []TronTaskCommit     `json:"commits" bson:"commits"`
	DevAttempts   int                  `json:"dev_attempts" bson:"dev_attempts"` // Max 3
	QAResult      *TronQAResult        `json:"qa_result" bson:"qa_result"`
	CostUSD       float64              `json:"cost_usd" bson:"cost_usd"`     // Total cost of this task
	TokensUsed    int64                `json:"tokens_used" bson:"tokens_used"`
	StartedAt     *time.Time           `json:"started_at" bson:"started_at"`
	CompletedAt   *time.Time           `json:"completed_at" bson:"completed_at"`
	CreatedAt     time.Time            `json:"created_at" bson:"created_at"`
	UpdatedAt     time.Time            `json:"updated_at" bson:"updated_at"`
}

// UpdateTronTaskRequest is the request for updating a task
type UpdateTronTaskRequest struct {
	Status   TronTaskStatus   `json:"status,omitempty"`
	Priority TronTaskPriority `json:"priority,omitempty"`
}

// TronTaskListResponse is the response for listing tasks
type TronTaskListResponse struct {
	Tasks []TronTask `json:"tasks"`
	Total int64      `json:"total"`
	Page  int        `json:"page"`
	Limit int        `json:"limit"`
}
